language: go

sudo: false

before_install:
  - go get github.com/mattn/goveralls

matrix:
  include:
    - go: "1.13.x"
      env: GO111MODULE=on
    - go: "1.12.x"
      env: GO111MODULE=on
    - go: tip
  script:
    - ./.travis.gofmt.sh
    - ./.travis.govet.sh
    - go test -v -race $(go list ./... | grep -v vendor)
    - $GOPATH/bin/goveralls -service=travis-ci